DROP FUNCTION IF EXISTS Задание1;
DROP FUNCTION IF EXISTS Задание2;
DROP FUNCTION IF EXISTS Задание3;
DROP FUNCTION IF EXISTS Задание4;
DROP FUNCTION IF EXISTS Задание5;
DROP FUNCTION IF EXISTS Задание6;
DROP FUNCTION IF EXISTS Задание7;
DROP FUNCTION IF EXISTS Задание8;
DROP FUNCTION IF EXISTS Задание9;
DROP FUNCTION IF EXISTS Задание10;
DROP FUNCTION IF EXISTS IsPalindrom;
DROP FUNCTION IF EXISTS Quarter;
DROP FUNCTION IF EXISTS IsPrime;
GO

PRINT 'Все функции задания успешно удалены.';
