CREATE PROC Swap
    @X AS FLOAT OUTPUT,
    @Y AS FLOAT OUTPUT
AS
BEGIN
    DECLARE @Temp AS FLOAT
    SET @Temp = @X
    SET @X = @Y
    SET @Y = @Temp
END
GO

DECLARE @A AS FLOAT = 5.5
DECLARE @B AS FLOAT = 3.2
EXECUTE Swap @A OUTPUT, @B OUTPUT
SELECT @A AS X, @B AS Y
